### ISSUE TITLE
Containers fail on starting - Nextcloud AIO v1.7.0

### ISSUE THREAD

**Issue by dcbuser** [nextcloud/all-in-one#1000]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Provisioned fresh Ubuntu server My Ubuntu 22.04 LTS Profile – GRUB 2 with 2 cores, 4GB Ram and 80GB HDD
2. Ran Nextcloud AIO v1.7.0, entered password and tried starting containers
3.  2 x container wont start - see below

### Expected behavior 
All containers start / run

### Actual behavior 

Apache - Tries starting / gets stuck
Error = Waiting for Nextcloud to start...
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Name or service not known

Database Running OK

Nextcloud - Tries starting / gets stuck 
Error = Configuring Redis as session handler
Appdata is not present. Did you maybe change the datadir after aio was first started?
psql: error: connection to server at "nextcloud-aio-database" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user "oc_nextcloud"

Redis Running OK

### Host OS 
Linode server - Ubuntu 22.04 LTS 

#### Nextcloud AIO version 
AIO v1.7.0

#### Current channel 
Latest

**Comment by w4itey** [comment]
I have also been dealing with this issue.

**Comment by w4itey** [comment]
I dunno know if this helps but I tried to do the manual install and had to change the postgres sql user in the lastest.yml file from nextcloud to oc_nextcloud and everything started working

**Comment by szaimen** [comment]
This should be fixed with 1.7.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by dcbuser** [comment]
Thanks Simon,

Any ETA on beta timing and release of 1.7.1?

(Wont hold you to it : )

**Comment by szaimen** [comment]
See https://github.com/nextcloud/all-in-one/issues/1012. Planned is currently to release it oon 24.08.

**Comment by willyamcts** [comment]
Hi Simon,

I tested now release 1.71 and error persists

In container nextcloud-aio-nextcloud:
```
Next OC\DB\Exceptions\DbalException: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "nextcloud-aio-database" (172.19.0.5), port 5432 failed: FATAL:  password authentication failed for user "oc_nextcloud" in /var/www/html/lib/private/DB/Exceptions/DbalException.php:71
Stack trace:
#0 /var/www/html/lib/private/DB/ConnectionAdapter.php(59): OC\DB\Exceptions\DbalException::wrap(Object(Doctrine\DBAL\Exception))
#1 /var/www/html/lib/private/legacy/OC_DB.php(55): OC\DB\ConnectionAdapter->prepare('SHOW SERVER_VER...', NULL, NULL)
#2 /var/www/html/lib/private/legacy/OC_DB.php(128): OC_DB::prepare('SHOW SERVER_VER...', NULL, NULL)
#3 /var/www/html/lib/private/legacy/OC_Util.php(759): OC_DB::executeAudited(Array)
#4 /var/www/html/lib/private/legacy/OC_Util.php(739): OC_Util::checkDatabaseVersion()
#5 /var/www/html/lib/private/Console/Application.php(157): OC_Util::checkServer(Object(OC\SystemConfig))
#6 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/occ(11): require_once('/var/www/html/c...')
#8 {main}installing of nextcloud failed!
Waiting for the database to start...
psql: error: connection to server at "nextcloud-aio-database" (172.19.0.5), port 5432 failed: FATAL:  password authentication failed for user "oc_nextcloud"
Waiting for the database to start...
```


in container nextcloud-aio-database:
```
2022-08-25 23:42:33.359 UTC [38] FATAL:  password authentication failed for user "oc_nextcloud"
2022-08-25 23:42:33.359 UTC [38] DETAIL:  Role "oc_nextcloud" does not exist.
        Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```

**Comment by tanmaywadhwa** [comment]
Facing the same issue as well

**Comment by no-ones-there** [comment]
Same issue for me. For testing I destroyed and recreated the master container (while leaving db and nextcloud intact) and issue persisted.

**Comment by dcbuser** [comment]
Hi guys, so looks like changing timezone on AIO setup screen causes the issue (no idea why). 

To confirm, I have created 2 x new Nextcloud servers from scratch. On reaching the domain and optional addon setup screen the timezone is left blank.  The Apache and Nextcloud containers are last to start but they reach "running" status within 1 min with no errors in the logs!  Hope this helps : )
