### ISSUE TITLE
Starting error: "path /mnt is mounted on / but it is not a shared mount"

### ISSUE THREAD

**Issue by reply-nick** [nextcloud/all-in-one#3057]
#### Other valuable info:

After[ #2601](https://github.com/nextcloud/all-in-one/pull/2601) change, I am getting this error:

```Message: Server error: `POST http://localhost/v1.41/containers/nextcloud-aio-nextcloud/start` resulted in a `500 Internal Server Error` response: {&quot;message&quot;:&quot;path /mnt is mounted on / but it is not a shared mount&quot;}```

Are there any workarounds for this?

**Comment by szaimen** [comment]
Hi, I found this: https://medium.com/codemonday/docker-erro-is-mounted-on-but-it-is-not-a-shared-mount-bb8b20dc2b8d

Does using `--env NEXTCLOUD_MOUNT="/mnt"` make it work?

**Comment by reply-nick** [comment]
hello!, 

> Hi, I found this: https://medium.com/codemonday/docker-erro-is-mounted-on-but-it-is-not-a-shared-mount-bb8b20dc2b8d
> 
> Does using `--env NEXTCLOUD_MOUNT="/mnt"` make it work?

Hello. Yes, I have tried it. No luck. :(

**Comment by Franz36** [comment]
I am getting the same error. 
(I am using AIO with rootless docker).

**Comment by MartinM01** [comment]
I am getting the same error.
I changed also NEXTCLOUD_MOUNT=/mnt in my docker-compose.yml, but the error persists.

**Comment by sodomak** [comment]
Same here (Alpine as host).

**Comment by sodomak** [comment]
Fixed (for me).
Check if output of `# findmnt -o TARGET,PROPAGATION -R /mnt`  looks like this:                                                                                                                                 
```
TARGET          PROPAGATION                                                                                                   
/mnt            private  
```
If so, run `findmnt -o TARGET,PROPAGATION -R /mnt`

Now, output of `findmnt` should change to
```
TARGET          PROPAGATION                                                                                                   
/mnt            shared  
```
and containers should start normally.

**Comment by massa007** [comment]
Same issue here with Alpine, unpriviliged LXC, AIO v6.4.
@sodomak I do not get any output with your command unfortunately...

**Comment by sodomak** [comment]
@massa007 Do you run it as root?

BTW I realized I pasted wrong command to fix the propagation, edited.

**Comment by massa007** [comment]
Yep I executed with root! 
I just realised that /mnt is not mounted anyhow so it cannot find it of course. Nevertheless I still get this error even though it doesn´t make sense...

**Comment by reply-nick** [comment]
`mount --make-rshared /` did the trick for me

**Comment by massa007** [comment]
Yep, that did work!

**Comment by MartinM01** [comment]
Hm,
Even with ` mount --make-rshared /`` is not recusiv shared. 
`findmnt -o TARGET,PROPAGATION /
TARGET PROPAGATION
/      shared`

The error persists! Hm I´m not sure why I can´t change the propagation.

**Comment by 0slav** [comment]
I'm having the same issue here.
Host: Ubuntu 22.04.3 LTS, snap version of docker.

I've tried every proposed solution in this issue without any luck. When I run `findmnt -o TARGET,PROPAGATION`, all mounts are listed as `shared` (except for `/run/snapd/ns` but making it rshared did not help either.)

For now I'm kicking the can down the road at v. 6.3.

**Comment by hanssliver** [comment]
there is also this problem when updating to 6,4

target start
```
docker run \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 448:8080 \
-e APACHE_PORT=446 \
-e NEXTCLOUD_DATADIR="/ncdata/ncdata" \
-e NEXTCLOUD_MOUNT="/mnt/" \
-e COLLABORA_SECCOMP_DISABLED=true \
-e NEXTCLOUD_UPLOAD_LIMIT=15G \
-e NEXTCLOUD_MAX_TIME=7200 \
-e NEXTCLOUD_MEMORY_LIMIT=768M \
-e TALK_PORT=3478 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
nextcloud/all-in-one:latest
```

change to `-e NEXTCLOUD_DATADIR="nextcloud_aio_nextcloud_datadir" \`
or del `-e NEXTCLOUD_MOUNT="/mnt/" \`
not work

```
findmnt -o TARGET,PROPAGATION -R /ncdata
TARGET  PROPAGATION
/ncdata shared
```

/ncdata is mount btrfs


work if del `-e NEXTCLOUD_DATADIR="nextcloud_aio_nextcloud_datadir" \`

**Comment by szaimen** [comment]
For everyone that runs into this issue, can you all please post the outout of `sudo docker inspect nextcloud-aio-mastercontainer` ? Thanks!

**Comment by 0slav** [comment]
Sure thing!
```
>sudo docker inspect nextcloud-aio-mastercontainer
[
    {
        "Id": "821601826aceabf3e2a42d96ffc638ef33b1c147b8b5d2c333e16b4438e0769f",
        "Created": "2023-08-09T14:36:56.335645248Z",
        "Path": "/start.sh",
        "Args": [
            "/usr/bin/supervisord",
            "-c",
            "/supervisord.conf"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 399512,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-08-09T14:45:01.079190031Z",
            "FinishedAt": "2023-08-09T14:44:53.062526579Z",
            "Health": {
                "Status": "starting",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2023-08-09T14:42:38.608563677Z",
                        "End": "2023-08-09T14:42:38.788607228Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2023-08-09T14:43:09.193859493Z",
                        "End": "2023-08-09T14:43:09.367759733Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2023-08-09T14:43:39.58760042Z",
                        "End": "2023-08-09T14:43:39.906334291Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2023-08-09T14:44:10.312644354Z",
                        "End": "2023-08-09T14:44:10.507091242Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2023-08-09T14:44:40.798472176Z",
                        "End": "2023-08-09T14:44:41.060814843Z",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:e138454d9cec8a3139efab019776c23aabb905369becbc51628c155d48f45504",
        "ResolvConfPath": "/var/snap/docker/common/var-lib-docker/containers/821601826aceabf3e2a42d96ffc638ef33b1c147b8b5d2c333e16b4438e0769f/resolv.conf",
        "HostnamePath": "/var/snap/docker/common/var-lib-docker/containers/821601826aceabf3e2a42d96ffc638ef33b1c147b8b5d2c333e16b4438e0769f/hostname",
        "HostsPath": "/var/snap/docker/common/var-lib-docker/containers/821601826aceabf3e2a42d96ffc638ef33b1c147b8b5d2c333e16b4438e0769f/hosts",
        "LogPath": "/var/snap/docker/common/var-lib-docker/containers/821601826aceabf3e2a42d96ffc638ef33b1c147b8b5d2c333e16b4438e0769f/821601826aceabf3e2a42d96ffc638ef33b1c147b8b5d2c333e16b4438e0769f-json.log",
        "Name": "/nextcloud-aio-mastercontainer",
        "RestartCount": 1,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "nextcloud_aio_mastercontainer:/mnt/docker-aio-config",
                "/var/run/docker.sock:/var/run/docker.sock:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8080"
                    }
                ],
                "8443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8443"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/snap/docker/common/var-lib-docker/overlay2/0b7ec7e1ada5313d12f2f882d710d76607265b2cb7491d70970dc26a8c1eed28-init/diff:/var/snap/docker/common/var-lib-docker/overlay2/a8b7386bef1caef3286c315fd233125971c437ada728f43a81953b92c7bb51ef/diff:/var/snap/docker/common/var-lib-docker/overlay2/55567a53b2a15cda550f34cd7b06262f290d61b90b3b987b882abc34de3dce8b/diff:/var/snap/docker/common/var-lib-docker/overlay2/bfb9869998e3142c03a9c78318cb87c10cb5448c1dc5170dcbe201a7bc34152a/diff:/var/snap/docker/common/var-lib-docker/overlay2/f7be8dcfb260d89c599b218c49bc87cc85dad58a1a5e5c5fa345ece227b4bfd4/diff:/var/snap/docker/common/var-lib-docker/overlay2/77cea9b24d5ac2ea4d2135338011639764008fad87bb521f5b91dc15859bb423/diff:/var/snap/docker/common/var-lib-docker/overlay2/efffdcd9036c61235afac23a58326219ea6e390b65753eeb2668aebb4bc69ad7/diff:/var/snap/docker/common/var-lib-docker/overlay2/5e236138bc48658a584285fd773604ed79aa3653392124a36b3c30d3aaffe615/diff:/var/snap/docker/common/var-lib-docker/overlay2/e85322dbc8905765d3c104e46b663fb8bdf857808499c736678ddb8a2611cebe/diff:/var/snap/docker/common/var-lib-docker/overlay2/d5befeb405235649783571b2fd561168427c6df6af48b63bb7d9f486a7e17bde/diff:/var/snap/docker/common/var-lib-docker/overlay2/1c13083fd44f03ba3d449382fc81bd2e7ea46d73f31bb74ef7dddc198d645d68/diff:/var/snap/docker/common/var-lib-docker/overlay2/8eec7c1e51d86426d16d535df07182c10ffd7b22102c9389c9a0b46fb010f965/diff:/var/snap/docker/common/var-lib-docker/overlay2/51e251abe65e14435000295df68bcafca0c9ceb2bd74a3af3673a93073a4a959/diff:/var/snap/docker/common/var-lib-docker/overlay2/76c65e11421814248759d26a0a89933221e79ed9b887c1a954c2b8f5bd938d42/diff:/var/snap/docker/common/var-lib-docker/overlay2/2ac6893e1b450ef92fa89b359941c3373bf98cfdd2a47f5f4abc3af1fa351636/diff:/var/snap/docker/common/var-lib-docker/overlay2/a9b1b86e8527ba9a0e296fd85b883644cc867b164a01d57a2185d5b832c33798/diff:/var/snap/docker/common/var-lib-docker/overlay2/68a794d87fe4ba3b1ef63cdafe3236cd54609c0d188928d6aa8fe1d09535d655/diff:/var/snap/docker/common/var-lib-docker/overlay2/7b72a7b7c42eab39add7db459cfbb54d47fb81d5d7597264b7858fd173f0b25e/diff:/var/snap/docker/common/var-lib-docker/overlay2/5effcb247093a37b9a85b632531d959991e2bd22366cb7bc3c4c38bdf6665aa7/diff",
                "MergedDir": "/var/snap/docker/common/var-lib-docker/overlay2/0b7ec7e1ada5313d12f2f882d710d76607265b2cb7491d70970dc26a8c1eed28/merged",
                "UpperDir": "/var/snap/docker/common/var-lib-docker/overlay2/0b7ec7e1ada5313d12f2f882d710d76607265b2cb7491d70970dc26a8c1eed28/diff",
                "WorkDir": "/var/snap/docker/common/var-lib-docker/overlay2/0b7ec7e1ada5313d12f2f882d710d76607265b2cb7491d70970dc26a8c1eed28/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "nextcloud_aio_mastercontainer",
                "Source": "/var/snap/docker/common/var-lib-docker/volumes/nextcloud_aio_mastercontainer/_data",
                "Destination": "/mnt/docker-aio-config",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "821601826ace",
            "Domainname": "",
            "User": "root",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "80/tcp": {},
                "8080/tcp": {},
                "8443/tcp": {},
                "9000/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "NEXTCLOUD_DATADIR=/mnt/ncdata",
                "NEXTCLOUD_MOUNT=/mnt/",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tdpkg-dev dpkg \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkgconf \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_LDFLAGS=-Wl,-O1 -pie",
                "GPG_KEYS=39B641343D8C104B2B146DC3F9C39DC0B9698544 E60913E4DF209907D8E30D96659A97C9CF2A795A 1198C0117593497A5EC5C199286AF1F9897469DC",
                "PHP_VERSION=8.2.8",
                "PHP_URL=https://www.php.net/distributions/php-8.2.8.tar.xz",
                "PHP_ASC_URL=https://www.php.net/distributions/php-8.2.8.tar.xz.asc",
                "PHP_SHA256=cfe1055fbcd486de7d3312da6146949aae577365808790af6018205567609801"
            ],
            "Cmd": [
                "/usr/bin/supervisord",
                "-c",
                "/supervisord.conf"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "/healthcheck.sh"
                ]
            },
            "Image": "nextcloud/all-in-one:latest",
            "Volumes": null,
            "WorkingDir": "/var/www/docker-aio",
            "Entrypoint": [
                "/start.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.centurylinklabs.watchtower.monitor-only": "true"
            },
            "StopSignal": "SIGQUIT"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9a7f7e2093cddd1a044649875399652f650e71e8c2150e49d7f4eec90dab9fc4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "80"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "8080"
                    }
                ],
                "8443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8443"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "8443"
                    }
                ],
                "9000/tcp": null
            },
            "SandboxKey": "/run/snap.docker/netns/9a7f7e2093cd",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "e525cb7fc9612770076760be7827d6e7866e30c4969a83230b1154e02d0e8592",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "085681e4dc9d660d9b4bc82c5deee2d541513d9637c22a36df17cd71143d7df5",
                    "EndpointID": "e525cb7fc9612770076760be7827d6e7866e30c4969a83230b1154e02d0e8592",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:03",
                    "DriverOpts": null
                },
                "nextcloud-aio": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "821601826ace"
                    ],
                    "NetworkID": "184010c16108bc00537e0626c7efa78707f87dae22ad197ee7dda5d79e53d478",
                    "EndpointID": "71e5ec97dfe148cb4f87212031fd61f67e4cc9cf0bc1b0c451037e92c1a49c9d",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by hanssliver** [comment]
worked if add `mount --make-rshared /` in `/etc/rc.local`
this is not a good solution

```
[
    {
        "Id": "f6df9b16701b9bb9c2202f0647fdfe1b2b6a306fa7b2d996c43ea6fc9506de4c",
        "Created": "2023-08-06T11:42:01.466802394Z",
        "Path": "/start.sh",
        "Args": [
            "/usr/bin/supervisord",
            "-c",
            "/supervisord.conf"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 6252,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-08-08T10:52:02.391668575Z",
            "FinishedAt": "2023-08-08T10:51:55.514931699Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2023-08-09T16:01:51.038445765Z",
                        "End": "2023-08-09T16:01:51.09022564Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2023-08-09T16:02:21.098363972Z",
                        "End": "2023-08-09T16:02:21.20380369Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2023-08-09T16:02:51.212258942Z",
                        "End": "2023-08-09T16:02:51.292329131Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2023-08-09T16:03:21.308602238Z",
                        "End": "2023-08-09T16:03:21.435037196Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2023-08-09T16:03:51.442843697Z",
                        "End": "2023-08-09T16:03:51.573542805Z",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:e138454d9cec8a3139efab019776c23aabb905369becbc51628c155d48f45504",
        "ResolvConfPath": "/opt/dockerd/containers/f6df9b16701b9bb9c2202f0647fdfe1b2b6a306fa7b2d996c43ea6fc9506de4c/resolv.conf",
        "HostnamePath": "/opt/dockerd/containers/f6df9b16701b9bb9c2202f0647fdfe1b2b6a306fa7b2d996c43ea6fc9506de4c/hostname",
        "HostsPath": "/opt/dockerd/containers/f6df9b16701b9bb9c2202f0647fdfe1b2b6a306fa7b2d996c43ea6fc9506de4c/hosts",
        "LogPath": "/opt/dockerd/containers/f6df9b16701b9bb9c2202f0647fdfe1b2b6a306fa7b2d996c43ea6fc9506de4c/f6df9b16701b9bb9c2202f0647fdfe1b2b6a306fa7b2d996c43ea6fc9506de4c-json.log",
        "Name": "/nextcloud-aio-mastercontainer",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "nextcloud_aio_mastercontainer:/mnt/docker-aio-config",
                "/var/run/docker.sock:/var/run/docker.sock:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "448"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "nextcloud_aio_mastercontainer",
                "Source": "/opt/dockerd/volumes/nextcloud_aio_mastercontainer/_data",
                "Destination": "/mnt/docker-aio-config",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "f6df9b16701b",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "80/tcp": {},
                "8080/tcp": {},
                "8443/tcp": {},
                "9000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "APACHE_PORT=446",
                "NEXTCLOUD_DATADIR=/ncdata/ncdata",
                "NEXTCLOUD_MOUNT=/mnt/",
                "COLLABORA_SECCOMP_DISABLED=true",
                "NEXTCLOUD_UPLOAD_LIMIT=15G",
                "NEXTCLOUD_MAX_TIME=7200",
                "NEXTCLOUD_MEMORY_LIMIT=768M",
                "TALK_PORT=3478",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tdpkg-dev dpkg \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkgconf \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_LDFLAGS=-Wl,-O1 -pie",
                "GPG_KEYS=39B641343D8C104B2B146DC3F9C39DC0B9698544 E60913E4DF209907D8E30D96659A97C9CF2A795A 1198C0117593497A5EC5C199286AF1F9897469DC",
                "PHP_VERSION=8.2.8",
                "PHP_URL=https://www.php.net/distributions/php-8.2.8.tar.xz",
                "PHP_ASC_URL=https://www.php.net/distributions/php-8.2.8.tar.xz.asc",
                "PHP_SHA256=cfe1055fbcd486de7d3312da6146949aae577365808790af6018205567609801"
            ],
            "Cmd": [
                "/usr/bin/supervisord",
                "-c",
                "/supervisord.conf"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "/healthcheck.sh"
                ]
            },
            "Image": "nextcloud/all-in-one:latest",
            "Volumes": null,
            "WorkingDir": "/var/www/docker-aio",
            "Entrypoint": [
                "/start.sh"
            ],
            "OnBuild": null,
            "Labels": {},
            "StopSignal": "SIGQUIT"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "c21dee7ff1e3415aaca6137ca3f15019544dd289100cea2df1b3240d3554b30f",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": null,
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "448"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "448"
                    }
                ],
                "8443/tcp": null,
                "9000/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/c21dee7ff1e3",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nextcloud-aio": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "f6df9b16701b"
                    ],
                    "NetworkID": "27a816860850a308fcb8c30317568b3d15373ef5ebc44480e7233a8a3536df84",
                    "EndpointID": "24fe53e1f70f1f8f61dff586ed5610e0b61e0f3d7f0ae7b4a64710b222ce8a4d",
                    "Gateway": "172.19.0.1",
                    "IPAddress": "172.19.0.7",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:13:00:07",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by szaimen** [comment]
So I had a look at the topic and apparently there is no way for us in AIO to fix this if your storage is set to private. So indeed you must set it to shared in order to fix this which is also the default for example on my test instance.
