### ISSUE TITLE
Borg backup restore doesnt work anymore

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#4124]
See https://github.com/search?q=repo%3Anextcloud%2Fall-in-one+securityopt&type=code

**Comment by SergSel2006** [comment]
My production server has malfunction now and I am required to restore backup. So, we need some workarounds. Does new instance uses same restore mechanism as existing one? Need to check it out somewhere.

**Comment by szaimen** [comment]
I will try to publish a new beta release that included a fix tomorrow.

**Comment by punkyard** [comment]
hi
I came back to the AiO two days after the last container update
It was ans is still stuck there:

`Nextcloud AIO v7.11.0
 Daily backup currently running. ([Logs](https://myip:1234/api/docker/logs?id=nextcloud-aio-mastercontainer))
The whole process should not take more than a few minutes.`

NC works on the other hand, but seemed slower right after update

good luck @szaimen

**Comment by Alexander-Orellana** [comment]
Hi @szaimen I'm having this issue and need to restore my production server. Has this been pushed ?

**Comment by dsaderholm** [comment]
I'm also really need to restore my server. People are relying on it.

**Comment by Alexander-Orellana** [comment]
Yea I would say for me this is critical if not a blocker as I can't restore. I'm sure Simon is on it though.

**Comment by szaimen** [comment]
I pushed a fix to https://github.com/nextcloud/all-in-one/pull/4130. Will afterwards build a new beta version.

**Comment by szaimen** [comment]
I tested it and it seems to have done the trick. Now only waiting for https://github.com/nextcloud-releases/all-in-one/actions/runs/7693299469 and then I'll publish the new beta release.

**Comment by szaimen** [comment]
This is now fixed with v7.11.2 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by Alexander-Orellana** [comment]
Thank you @szaimen. I can now confirm that I was able to restore from backup. Your work is greatly appreciated!

**Comment by punkyard** [comment]
I shall try too then !

**Comment by punkyard** [comment]
yeah! it worked. NC seems a little faster than this morning, but still not very fast.

I pulled images and I'm surprised that the same versions are still running
AiO 7.11.0
NC 27.1.5

<img width="642" alt="Capture d’écran 2024-01-29 à 14 21 34" src="https://github.com/nextcloud/all-in-one/assets/59349105/7f5fd26d-312e-40f7-978a-1e209f182fe8">

**Comment by SergSel2006** [comment]
Thanks for the release!
Now my server is able to restore!
You're so effectively working

**Comment by punkyard** [comment]
hi and thanks
version 7.11.2 fiwed everything - the whole instance is running very much faster since

just Notify push won't start again

<img width="717" alt="Capture d’écran 2024-02-01 à 20 42 52" src="https://github.com/nextcloud/all-in-one/assets/59349105/ffa888db-6c8d-4c8d-9bb1-8e6714cc83cf">
