### ISSUE TITLE
AIO mastercontainer fails to start after update (20251128_084214) due to Docker socket connection error on Synology

### ISSUE THREAD

**Issue by deepschiff** [nextcloud/all-in-one#7223]
### Steps to reproduce

1. Run Nextcloud AIO on Synology DSM using the recommended docker compose.
2. Allow Watchtower to update the image nextcloud/all-in-one from version 20251031_122139 to 20251128_084214.

### Expected behavior

The nextcloud-aio-mastercontainer should start normally and connect to the Docker socket at /var/run/docker.sock to orchestrate the dependent AIO containers.

### Actual behavior

The mastercontainer immediately exits with a repeating error:

Did you maybe remove group read permissions for the docker socket?  
Cannot connect to the docker socket. Cannot proceed.

Even though:

1. The socket is correctly bind-mounted into the container
2. Docker itself is healthy and other containers can access the socket normally
3. The issue occurs before the container stays alive long enough to exec into it
4. Rolling back the mastercontainer image from latest → 20251031_122139 immediately resolves the issue, with no other configuration changes.

#### Host OS
Synology DSM (Container Manager), running on a Synology NAS.

#### Docker compose

```
services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest # This is the container image used. You can switch to ghcr.io/nextcloud-releases/all-in-one:beta if you want to help testing new releases. See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
    init: true # This setting makes sure that signals from main process inside the container are correctly forwarded to children. See https://docs.docker.com/reference/compose-file/services/#init
    restart: always # This makes sure that the container starts always together with the host OS. See https://docs.docker.com/reference/compose-file/services/#restart
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    network_mode: bridge # This adds the container to the same network as docker run would do. Comment this line and uncomment the line below and the networks section at the end of the file if you want to define a custom MTU size for the docker network
    # networks: ["nextcloud-aio"]
    ports:
      #- 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080 # This is the AIO interface, served via https and self-signed certificate. See https://github.com/nextcloud/all-in-one#explanation-of-used-ports
      # 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    # security_opt: ["label:disable"] # Is needed when using SELinux. See https://github.com/nextcloud/all-in-one#are-there-known-problems-when-selinux-is-enabled
    environment: # Is needed when using any of the options below
      # AIO_DISABLE_BACKUP_SECTION: false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
       APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
       APACHE_IP_BINDING: 0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
       SKIP_DOMAIN_VALIDATION: true
      # APACHE_ADDITIONAL_NETWORK: frontend_net # (Optional) Connect the apache container to an additional docker network. Needed when behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) running in a different docker network on same server. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      # COLLABORA_SECCOMP_DISABLED: false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # DOCKER_API_VERSION: 1.44 # You can adjust the internally used docker api version with this variable. ⚠️⚠️⚠️ Warning: please note that only the default api version (unset this variable) is supported and tested by the maintainers of Nextcloud AIO. So use this on your own risk and things might break without warning. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-internally-used-docker-api-version
      # FULLTEXTSEARCH_JAVA_OPTIONS: "-Xms1024M -Xmx1024M" # Allows to adjust the fulltextsearch java options. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-fulltextsearch-java-options
       NEXTCLOUD_DATADIR: /volume1/docker/nextcloud/data # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # NEXTCLOUD_MOUNT: /mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # NEXTCLOUD_UPLOAD_LIMIT: 16G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # NEXTCLOUD_MAX_TIME: 3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # NEXTCLOUD_MEMORY_LIMIT: 512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # NEXTCLOUD_TRUSTED_CACERTS_DIR: /path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nextcloud container (Useful e.g. for LDAPS) See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # NEXTCLOUD_STARTUP_APPS: deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      # NEXTCLOUD_ADDITIONAL_APKS: imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      # NEXTCLOUD_ENABLE_DRI_DEVICE: true # This allows to enable the /dev/dri device for containers that profit from it. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-acceleration-for-nextcloud
      # NEXTCLOUD_ENABLE_NVIDIA_GPU: true # This allows to enable the NVIDIA runtime and GPU access for containers that profit from it. ⚠️⚠️⚠️ Warning: this only works if an NVIDIA gpu is installed on the server. See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-acceleration-for-nextcloud.
      # NEXTCLOUD_KEEP_DISABLED_APPS: false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # SKIP_DOMAIN_VALIDATION: false # This should only be set to true if things are correctly configured. See https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-skip-the-domain-validation
      # TALK_PORT: 3478 # This allows to adjust the port that the talk container is using which is exposed on the host. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # WATCHTOWER_DOCKER_SOCKET_PATH: /volume1/docker/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
   # Optional: Caddy reverse proxy. See https://github.com/nextcloud/all-in-one/discussions/575
   # Alternatively, use Tailscale if you don't have a domain yet. See https://github.com/nextcloud/all-in-one/discussions/6817
   # Hint: You need to uncomment APACHE_PORT: 11000 above, adjust cloud.example.com to your domain and uncomment the necessary docker volumes at the bottom of this file in order to make it work
   # You can find further examples here: https://github.com/nextcloud/all-in-one/discussions/588
#   caddy:
#     image: caddy:alpine
#     restart: always
#     container_name: caddy
#     volumes:
#       - caddy_certs:/certs
#       - caddy_config:/config
#       - caddy_data:/data
#       - caddy_sites:/srv
#     network_mode: "host"
#     configs:
#       - source: Caddyfile
#         target: /etc/caddy/Caddyfile
# configs:
#   Caddyfile:
#     content: |
#       # Adjust cloud.example.com to your domain below
#       https://cloud.example.com:443 {
#         reverse_proxy localhost:11000
#       }
volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
  # caddy_certs:
  # caddy_config:
  # caddy_data:
  # caddy_sites:
 # Adjust the MTU size of the docker network. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-mtu-size-of-the-docker-network
# networks:
#   nextcloud-aio:
#     name: nextcloud-aio
#     driver_opts:
#       com.docker.network.driver.mtu: 1440
```

### Output of sudo docker logs nextcloud-aio-mastercontainer

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/bensc/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/bensc/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#467886" vlink="#96607D">

nextcloud-aio-mastercontainer |   |  
-- | -- | --
date | stream | content
11/29/2025 9:21 | stdout | If you are on TrueNas SCALE, see   https://github.com/nextcloud/all-in-one#can-i-run-aio-on-truenas-scale
11/29/2025 9:21 | stdout | If SELinux is enabled on your   host, see   https://github.com/nextcloud/all-in-one#are-there-known-problems-when-selinux-is-enabled
11/29/2025 9:21 | stdout | Did you maybe remove group read permissions for the docker socket? AIO   needs them in order to access the docker socket.
  |   |  
11/29/2025 9:21 | stdout | [0;31mCannot connect to the docker socket. Cannot proceed.[0m

</body>

</html>

### Other valuable info

1. This issue started exactly after Watchtower automatically updated the nextcloud-aio-mastercontainer image to 20251128_084214.
2. The previous image (20251031_122139) works flawlessly when re-run with the same configuration.
3. It appears that something in the 20251128_084214 mastercontainer image is preventing it from opening or using the Docker socket on Synology DSM environments.

**Comment by dlichtenberger** [comment]
Which Docker version ("docker version") are you running? 

The docker API version was bumped to 1.44 with the latest release: https://github.com/nextcloud/all-in-one/releases/tag/v12.1.4 

I had the same issue on a server running Debian Bookworm, which is currently on Docker 20 / API 1.41. Instead of trying the workaround listed in the release notes I updated the server to Debian Trixie (Docker 26 / API 1.45) which also solved the problem.

**Comment by MastaG** [comment]
Same here on my DS1821+
OS: DSM 7.2.2-72806 Update 5

```
# docker version
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        610b8d0
 Built:             Fri Jun 20 01:00:52 2025
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       bd0a34d
  Built:            Fri Jun 20 00:57:53 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        fea6458b8abe502f6228eab2e5a6678fcb5c3fb0
 runc:
  Version:          v1.1.7
  GitCommit:        0320c58
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00
```

I've tried setting `DOCKER_API_VERSION: 1.44`  but that did not the problem.

Here's my compose config:
```
version: "3.9"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest # This is the container image used. You can switch to ghcr.io/nextcloud-releases/all-in-one:beta if you want to help testing new releases. See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
    init: true # This setting makes sure that signals from main process inside the container are correctly forwarded to children. See https://docs.docker.com/reference/compose-file/services/#init
    restart: always # This makes sure that the container starts always together with the host OS. See https://docs.docker.com/reference/compose-file/services/#restart
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
    ports:
      - 8082:8080
    environment: # Is needed when using any of the options below
      AIO_DISABLE_BACKUP_SECTION: true # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      APACHE_IP_BINDING: 0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # APACHE_ADDITIONAL_NETWORK: frontend_net # (Optional) Connect the apache container to an additional docker network. Needed when behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) running in a different docker network on same server. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      COLLABORA_SECCOMP_DISABLED: true # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # FULLTEXTSEARCH_JAVA_OPTIONS: "-Xms1024M -Xmx1024M" # Allows to adjust the fulltextsearch java options. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-fulltextsearch-java-options
      NEXTCLOUD_DATADIR: /volume1/docker/nextcloud-aio/data # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # NEXTCLOUD_MOUNT: /mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      NEXTCLOUD_UPLOAD_LIMIT: 32G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # NEXTCLOUD_MAX_TIME: 3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      NEXTCLOUD_MEMORY_LIMIT: 4096M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # NEXTCLOUD_TRUSTED_CACERTS_DIR: /path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nextcloud container (Useful e.g. for LDAPS) See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # NEXTCLOUD_STARTUP_APPS: deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      # NEXTCLOUD_ADDITIONAL_APKS: imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      # NEXTCLOUD_ENABLE_DRI_DEVICE: true # This allows to enable the /dev/dri device for containers that profit from it. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-acceleration-for-nextcloud
      # NEXTCLOUD_ENABLE_NVIDIA_GPU: true # This allows to enable the NVIDIA runtime and GPU access for containers that profit from it. ⚠️⚠️⚠️ Warning: this only works if an NVIDIA gpu is installed on the server. See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-acceleration-for-nextcloud.
      # NEXTCLOUD_KEEP_DISABLED_APPS: false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # SKIP_DOMAIN_VALIDATION: false # This should only be set to true if things are correctly configured. See https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-skip-the-domain-validation
      TALK_PORT: 3488 # This allows to adjust the port that the talk container is using which is exposed on the host. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # WATCHTOWER_DOCKER_SOCKET_PATH: /var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      DOCKER_API_VERSION: 1.44
```
Master container log:
```
Trying to fix docker.sock permissions internally...
Adding internal www-data to group root
Cannot connect to the docker socket. Cannot proceed.
Did you maybe remove group read permissions for the docker socket? AIO needs them in order to access the docker socket.
If SELinux is enabled on your host, see https://github.com/nextcloud/all-in-one#are-there-known-problems-when-selinux-is-enabled
If you are on TrueNas SCALE, see https://github.com/nextcloud/all-in-one#can-i-run-aio-on-truenas-scale
```

**Comment by Zoey2936** [comment]
https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-adjust-the-internally-used-docker-api-version

**Comment by MastaG** [comment]
Yeah I figured it out as it seems Synology's DSM uses an older docker.
The docker version says its API is on version 1.43.

So I've fixed it by setting:
`DOCKER_API_VERSION: 1.43`
 
It now runs:
```
Trying to fix docker.sock permissions internally...
Adding internal www-data to group root
DOCKER_API_VERSION was found to be set to '1.43'.
Please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
So you run on your own risk and things might break without warning.
```

Lets hope it won't break in the near future when AIO starts requiring more recent docker API versions....

**Comment by humfry** [comment]
> So I've fixed it by setting:
> DOCKER_API_VERSION: 1.43

Can you tell where and how set this?
I tried to role back, but this is realy cumbersome and after some trials still not working as I failed to import old settings.
Thank you.

**Comment by Makkaronikopf** [comment]
> > So I've fixed it by setting:
> > DOCKER_API_VERSION: 1.43
> 
> Can you tell where and how set this? I tried to role back, but this is realy cumbersome and after some trials still not working as I failed to import old settings. Thank you.

You can just add the environment variable and are good to go:
    environment:
      - DOCKER_API_VERSION=1.43

Had the same problem since the update and this fixed it for me.

**Comment by humfry** [comment]
Ok, thanks for the tip.

Unfortunately to change or add something you have to clone the existing image.
Then starting the new one is not possible because of TCP conflicts.
Ok, deleting the old one.

Then at least on start up it shows a warning about the version, but goes ahead.

Then the name of the mastercontainer cannot be found:

First, 
<img width="1018" height="125" alt="Image" src="https://github.com/user-attachments/assets/93fbd580-bdc8-4dd7-b5a6-9ce4cfc7f895" />

Before it was nextcloud-aio-mastercontainer-1
changing the name does not fix this issue.

And additionally there are missing virtual links in this list wich cannot be added with synologies hard link file option.

The problem here is the not well tested nextcloud update with Synologies inability to role back or let the user change settings.

For me nextcload was a nice try. 
I'm stopping.
Thanks.

**Comment by ralfboernemeier** [comment]
> > > So I've fixed it by setting:
> > > DOCKER_API_VERSION: 1.43
> > 
> > 
> > Can you tell where and how set this? I tried to role back, but this is realy cumbersome and after some trials still not working as I failed to import old settings. Thank you.
> 
> You can just add the environment variable and are good to go: environment: - DOCKER_API_VERSION=1.43
> 
> Had the same problem since the update and this fixed it for me.

I have entered your suggested change in compose.yaml
`
   environment: # Is needed when using any of the options below  
       APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md  
       APACHE_IP_BINDING: 127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
       NEXTCLOUD_MEMORY_LIMIT: 512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
       DOCKER_API_VERSION: 1.41
`
However, I continue to receive the following error when starting the master container:
`
Trying to fix docker.sock permissions internally...
Adding internal www-data to group ntp
Cannot connect to the docker socket. Cannot proceed.
Did you maybe remove group read permissions for the docker socket? AIO needs them in order to access the docker socket.
If SELinux is enabled on your host, see https://github.com/nextcloud/all-in-one#are-there-known-problems-when-selinux-is-enabled
If you are on TrueNas SCALE, see https://github.com/nextcloud/all-in-one#can-i-run-aio-on-truenas-scale
Cannot connect to the docker socket. Cannot proceed.
`
I have Debian bookworm on a Raspberry Pi with docker version "20.10.24+dfsg1". 
Any ideas?

**Comment by mikebakke** [comment]
I hit this today as well - server running bookworm and I had all the docker.sock errors. Added -        

- DOCKER_API_VERSION=1.41 to my compose and it started although it threw the following warnings:
nextcloud-aio-mastercontainer | Trying to fix docker.sock permissions internally...
nextcloud-aio-mastercontainer | Creating docker group internally with id 112
nextcloud-aio-mastercontainer | DOCKER_API_VERSION was found to be set to '1.41'.
nextcloud-aio-mastercontainer | Please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
nextcloud-aio-mastercontainer | So you run on your own risk and things might break without warning.
nextcloud-aio-mastercontainer | Initial startup of Nextcloud All-in-One complete!

I guess I need to upgrade to Trixie, unfortunately I have quite a few servers in this state atm.

**Comment by ralfboernemeier** [comment]
Where did you set/add the DOCKER_API_VERSION? I tried it also with 1.41 in compose.yaml, but unfortunately my Mastercontainer did not start. Can you share your command/compose.yaml please?
Anyway, I will also try to upgrade from bookworm to Trixie ;-)

**Comment by ralfboernemeier** [comment]
It now works for me too with DOCKER_API_VERSION: 1.41 in compose.yaml. It was probably a special character after the variable name, which meant that the variable was not processed.  
```
    environment: # Is needed when using any of the options below
       APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
       APACHE_IP_BINDING: 127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
       NEXTCLOUD_MEMORY_LIMIT: 512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
       DOCKER_API_VERSION: 1.41 # see https://github.com/nextcloud/all-in-one/issues/7223#issuecomment-3592745160
```

**Comment by samhonarvar** [comment]
I run on ubuntu and I was on docker 24. 

I did the following:

`docker --version` -- verify the docker version you are on
`docker stop $(docker ps -aq)`
`sudo apt update`
`sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin`
`docker --version` -- verify docker is updated to latest (29)
`sudo systemctl restart docker`

**Comment by mpanhans** [comment]
The steps from @samhonarvar fixed the issue for me on Ubuntu server. Thank you!

**Comment by MastaG** [comment]
Exactly!

Nextcloud AIO now defaults to docker api version 1.44.

And remember, we all run it on different docker or podman versions.

On podman it still seems to work for me, so I guess my podman setup is still compatible with docker api version 1.44.

In case of docker you can see which api version it supports by issuing the following command:
`docker version`

It should show something like this:
```
Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
```

So in my case docker doesn't support api 1.44.
It only goes up to 1.43.
That's why it failed to start and needed to specify:
```
environment: # Is needed when using any of the options below
       DOCKER_API_VERSION: 1.43 # see https://github.com/nextcloud/all-in-one/issues/7223#issuecomment-3592745160
```

So make sure to check for youself and don't just copy a version number from here .
Specifying a lower api version number can actually  break things even sooner.

**Comment by szaimen** [comment]
Hi, the compatibility check should now be improved with v12.2.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by Noctisik** [comment]
In my case it was solved by pulling older version of mastercontainer (nextcloud/all-in-one:20240925_080419).

I did:

docker rm -f nextcloud-aio-mastercontainer

docker run -d \
  --sig-proxy=false \
  --name nextcloud-aio-mastercontainer \
  --restart always \
  -p 8080:8080 \
  -p 7867:7867/udp \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -v /volume1/docker/nextcloud-aio:/mnt/data \
  -v nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
  -v /volume1/DATA/nextcloud_backup:/mnt/backups \
  -e SKIP_DOMAIN_VALIDATION=true \
  -e APACHE_PORT=[yourport] \
  -e APACHE_IP_BINDING=0.0.0.0 \
  -e WATCHTOWER_DOCKER_SOCKET_PATH="/var/run/docker.sock" \
  nextcloud/all-in-one:20240925_080419

**Comment by szaimen** [comment]
> In my case it was solved by pulling older version of mastercontainer (nextcloud/all-in-one:20240925_080419

I fear this is not a permanent solution as the dependencies will get more and more outdated over time.

And FYI: this version is now already one year old. I would highly recommend to upgrade to  a more recent version.

**Comment by oustedaisse** [comment]
> Hi, the compatibility check should now be improved with v12.2.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

Hello, v12.2.0 Beta breaks compatibility (again) with Synology here.

Starting nextcloud-aio-mastercontainer in 12.1.4 : 

```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 65536
DOCKER_API_VERSION was found to be set to '1.43'.
Please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
So you run on your own risk and things might break without warning.
WARNING: No kernel memory TCP limit support
[...]
WARNING: No blkio throttle.write_iops_device support
Initial startup of Nextcloud All-in-One complete!
```

No problem.

Starting nextcloud-aio-mastercontainer in 12.2.0 : 

```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 65536
DOCKER_API_VERSION was found to be set to '1.43'.
Please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
So you run on your own risk and things might break without warning.
Docker API v1.44 is not supported by your docker engine. Cannot proceed. Please upgrade your docker engine if you want to run Nextcloud AIO!
Alternatively, set the DOCKER_API_VERSION environmental variable to a compatible version.
However please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
See https://github.com/nextcloud/all-in-one#how-to-adjust-the-internally-used-docker-api-version
```

It failed, and loop at this point.

Same Docker compose file with "DOCKER_API_VERSION: 1.43".

Sorry !

**Comment by tamet83** [comment]
Hi, I confirm the problem still not solved.
On my DS923+ I still need to use the "DOCKER_API_VERSION: 1.43" within my Yaml config.

I don't understand if there is something else to do.

Thank you

**Comment by szaimen** [comment]
> > Hi, the compatibility check should now be improved with v12.2.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
> 
> Hello, v12.2.0 Beta breaks compatibility (again) with Synology here.
> 
> Starting nextcloud-aio-mastercontainer in 12.1.4 :
> 
> ```
> Trying to fix docker.sock permissions internally...
> Creating docker group internally with id 65536
> DOCKER_API_VERSION was found to be set to '1.43'.
> Please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
> So you run on your own risk and things might break without warning.
> WARNING: No kernel memory TCP limit support
> [...]
> WARNING: No blkio throttle.write_iops_device support
> Initial startup of Nextcloud All-in-One complete!
> ```
> 
> No problem.
> 
> Starting nextcloud-aio-mastercontainer in 12.2.0 :
> 
> ```
> Trying to fix docker.sock permissions internally...
> Creating docker group internally with id 65536
> DOCKER_API_VERSION was found to be set to '1.43'.
> Please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
> So you run on your own risk and things might break without warning.
> Docker API v1.44 is not supported by your docker engine. Cannot proceed. Please upgrade your docker engine if you want to run Nextcloud AIO!
> Alternatively, set the DOCKER_API_VERSION environmental variable to a compatible version.
> However please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
> See https://github.com/nextcloud/all-in-one#how-to-adjust-the-internally-used-docker-api-version
> ```
> 
> It failed, and loop at this point.
> 
> Same Docker compose file with "DOCKER_API_VERSION: 1.43".
> 
> Sorry !

Hey, thanks for testing and coming back to me!

I have an additional fix for this in https://github.com/nextcloud/all-in-one/pull/7280. Will create a new beta release for this soon.

**Comment by szaimen** [comment]
> > > Hi, the compatibility check should now be improved with v12.2.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
> > 
> > 
> > Hello, v12.2.0 Beta breaks compatibility (again) with Synology here.
> > Starting nextcloud-aio-mastercontainer in 12.1.4 :
> > ```
> > Trying to fix docker.sock permissions internally...
> > Creating docker group internally with id 65536
> > DOCKER_API_VERSION was found to be set to '1.43'.
> > Please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
> > So you run on your own risk and things might break without warning.
> > WARNING: No kernel memory TCP limit support
> > [...]
> > WARNING: No blkio throttle.write_iops_device support
> > Initial startup of Nextcloud All-in-One complete!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No problem.
> > Starting nextcloud-aio-mastercontainer in 12.2.0 :
> > ```
> > Trying to fix docker.sock permissions internally...
> > Creating docker group internally with id 65536
> > DOCKER_API_VERSION was found to be set to '1.43'.
> > Please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
> > So you run on your own risk and things might break without warning.
> > Docker API v1.44 is not supported by your docker engine. Cannot proceed. Please upgrade your docker engine if you want to run Nextcloud AIO!
> > Alternatively, set the DOCKER_API_VERSION environmental variable to a compatible version.
> > However please note that only v1.44 is officially supported and tested by the maintainers of Nextcloud AIO.
> > See https://github.com/nextcloud/all-in-one#how-to-adjust-the-internally-used-docker-api-version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It failed, and loop at this point.
> > Same Docker compose file with "DOCKER_API_VERSION: 1.43".
> > Sorry !
> 
> Hey, thanks for testing and coming back to me!
> 
> I have an additional fix for this in [#7280](https://github.com/nextcloud/all-in-one/pull/7280). Will create a new beta release for this soon.

This is now released with v12.2.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by oustedaisse** [comment]
> > Hey, thanks for testing and coming back to me!
> > I have an additional fix for this in [#7280](https://github.com/nextcloud/all-in-one/pull/7280). Will create a new beta release for this soon.
> 
> This is now released with v12.2.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

Can confirm that v12.2.1 did the trick! Thanks for quick reply and fix :)

**Comment by tamet83** [comment]
Hi,
for the sake of clarity, could you tell me whether adding an environment variable is considered a robust solution, or if you would recommend something else?
The main issue with Synology devices is that they use a very old version of Docker, so I’m not sure whether this workaround can be relied on in the long term.
Thanks to anyone who can provide some guidance.

**Comment by Noctisik** [comment]
> > In my case it was solved by pulling older version of mastercontainer (nextcloud/all-in-one:20240925_080419
> 
> I fear this is not a permanent solution as the dependencies will get more and more outdated over time.
> 
> And FYI: this version is now already one year old. I would highly recommend to upgrade to a more recent version.

I can agree with you on that, but for this moment the only newer version I found working was with tag nextcloud/all-in-one:20250325_084656. It's v10.9.0 only.

Also tried latest with -e DOCKER_API_VERSION=1.43 - mastercontainer starts, but fails to start other containers.

**Comment by MrReSc** [comment]
@szaimen I had the same problem. I set the environment variable DOCKER_API_VERSION=1.43 and was able to restart the container and update everything. Now Nextcloud AIO v12.3.0 is running. If I remove DOCKER_API_VERSION=1.43 from docker-compose.yaml again, I get the same error. How can I solve this permanently?

Synology DS918+

**Comment by szaimen** [comment]
> [@szaimen](https://github.com/szaimen) I had the same problem. I set the environment variable DOCKER_API_VERSION=1.43 and was able to restart the container and update everything. Now Nextcloud AIO v12.3.0 is running. If I remove DOCKER_API_VERSION=1.43 from docker-compose.yaml again, I get the same error. How can I solve this permanently?

You cannot. `DOCKER_API_VERSION=1.43` is required on Synology until they upgrade their docker packages to v25 or higher.
